### PR TITLE
fix: azbatch pool create

### PR DESCRIPTION
**Pull request by jakevc**
### Description

1. Overhauls the batch pool creation to use only the azure-mgmt-batch sdk. 

The azure-mgmt-batch SDK now supports all the features of pool creation that we need (namely the addition of the managed identity to the batch pool). Using the azure-mgmt-batch SDK entirely now for pool creation prevents the weird work around with adding the identity to the pool after creation, it can now done all at once. Cleaner, and also prevents a nasty edge case bug with the managed identity not being picked up on the batch nodes.

2. Cleanup 

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by jakevc** [comment]
@vsoch  need help. Since the Snakemake Executor interface was changed a few commits back, I think the behavior of that RemoteExecutor you put in there is still a little different from the one I was using, where now my simple test fails to stage the files into and out of blob, and expects them to be on my local execution environment rather than the remote. 

For reference my test:
```
rule all:
    input: "test.txt"

rule touch_text:
    output:
        "test.txt"
    shell:
        "echo 'test' > {output}"
```

The command:
```
snakemake \
    -pf \
    --snakefile test-small.smk \
    --verbose \
    --jobs 1 \
    --default-remote-prefix $AZ_BLOB_PREFIX \
    --use-conda \
    --default-remote-provider AzBlob \
    --envvars AZ_BLOB_ACCOUNT_URL \
    --az-batch \
    --container-image snakemake/snakemake \
    --az-batch-account-url $AZ_BATCH_ACCOUNT_URL
```

The Logs:
```
Building DAG of jobs...
AzBatchConfig: { 'autoscale_formula': '\n'
                       '        $samples = '
                       '$PendingTasks.GetSamplePercent(TimeInterval_Minute * '
                       '5);\n'
                       '        $tasks = $samples < 70 ********************',
  'batch_account_key': '**********',
  'batch_account_name': 'eacribioinfo',
  'batch_account_url': 'https://eacribioinfo.westus2.batch.azure.com/',
  'batch_node_communication_mode': None,
  'batch_node_fill_type': 'spread',
  'batch_node_start_task_sasurl': 'https://eacriprodpipelines.blob.core.windows.net/configuration/start-task.sh**********',
  'batch_pool_image_offer': 'ubuntu-server-container',
  'batch_pool_image_publisher': 'microsoft-azure-batch',
  'batch_pool_image_sku': '20-04-lts',
  'batch_pool_node_count': 1,
  'batch_pool_subnet_id': '/subscriptions/6a2f9eff-0413-4598-a5ca-ed6b6430a274/resourceGroups/rg-eacps-or-ppmc-eacri-westus2/providers/Microsoft.Network/virtualNetworks/vnet-batch-eacri-bioinfo/subnets/batchnodepool',
  'batch_pool_vm_container_image': 'ubuntu',
  'batch_pool_vm_node_agent_sku_id': 'batch.node.ubuntu 20.04',
  'batch_pool_vm_size': 'Standard_D2_v3',
  'batch_tasks_per_node': 1,
  'container_registry_pass': None,
  'container_registry_url': 'https://eacribioinfoacr.azurecr.io',
  'container_registry_user': None,
  'managed_identity_client_id': '**********',
  'managed_identity_resource_id': '/subscriptions/6a2f9eff-0413-4598-a5ca-ed6b6430a274/resourceGroups/rg-eacps-or-ppmc-eacri-westus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mi-eacri-batchpool',
  'resource_file_prefix': 'resource-files',
  'resource_group': 'rg-eacps-or-ppmc-eacri-westus2',
  'subscription_id': '6a2f9eff-0413-4598-a5ca-ed6b6430a274'}
Created /tmp/snakemake-ztnt9vtz.tar.gz with the following contents: ['/data1/eacri-snakemake-tutorial/.gitignore', '/data1/eacri-snakemake-tutorial/src/plot-quals.py', '/data1/eacri-snakemake-tutorial/envs/stats.yml', '/data1/eacri-snakemake-tutorial/workflow.svg', '/data1/eacri-snakemake-tutorial/configure.sh', '/data1/eacri-snakemake-tutorial/envs/calling.yml', '/data1/eacri-snakemake-tutorial/README.md', '/data1/eacri-snakemake-tutorial/run.sh', '/data1/eacri-snakemake-tutorial/envs/mapping.yml', '/data1/eacri-snakemake-tutorial/Snakefile', '/data1/eacri-snakemake-tutorial/test-small.smk']
Using managed identity batch authentication...
Creating pool: snakepool-2023-0818T15-57-45
Creating job snakejob-2023-0818T15-57-45
Using shell: /usr/bin/bash
Job stats:
job           count
----------  -------
all               1
touch_text        1
total             2

Resources before job selection: {'_cores': 9223372036854775807, '_nodes': 3}
Ready jobs (1)
Select jobs to execute...
Selected jobs (1)
Resources after job selection: {'_cores': 9223372036854775806, '_nodes': 2}

[Fri Aug 18 15:57:49 2023]
rule touch_text:
    output: snaketest/test1/test.txt
    jobid: 1
    reason: Missing output files: snaketest/test1/test.txt
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=<TBD>

echo 'test' > snaketest/test1/test.txt
Added AzBatch task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf
Added AzBatch task: { 'additional_properties': {},
  'affinity_info': None,
  'application_package_references': None,
  'authentication_token_settings': None,
  'command_line': "/bin/bash -c 'tar xzf "
                  'resource-files/workdir-937ef838acd9dcc31238a57ddcece12956d8b927039ccd79bed1757649aba3e1.tar.gz '
                  '&& '
                  '\'AZ_BLOB_ACCOUNT_URL=\'"\'"\'https://eacriprodpipelines.blob.core.windows.net/**********\'"\'"\' '
                  'python -m snakemake --snakefile '
                  '\'"\'"\'test-small.smk\'"\'"\' --target-jobs '
                  '\'"\'"\'touch_text:\'"\'"\' --allowed-rules '
                  '\'"\'"\'touch_text\'"\'"\' --cores \'"\'"\'all\'"\'"\' '
                  '--attempt 1 --force-use-threads  --resources '
                  '\'"\'"\'mem_mb=1000\'"\'"\' \'"\'"\'mem_mib=954\'"\'"\' '
                  '\'"\'"\'disk_mb=1000\'"\'"\' \'"\'"\'disk_mib=954\'"\'"\'  '
                  '--force --keep-target-files --keep-remote '
                  '--max-inventory-time 0 --nocolor --notemp --no-hooks '
                  '--nolock --ignore-incomplete --rerun-triggers '
                  '\'"\'"\'software-env\'"\'"\' \'"\'"\'params\'"\'"\' '
                  '\'"\'"\'input\'"\'"\' \'"\'"\'code\'"\'"\' '
                  '\'"\'"\'mtime\'"\'"\' --skip-script-cleanup  --use-conda  '
                  '--conda-frontend \'"\'"\'mamba\'"\'"\' --wrapper-prefix '
                  '\'"\'"\'https://github.com/snakemake/snakemake-wrappers/raw/\'"\'"\' '
                  '--printshellcmds  --latency-wait 5 --scheduler '
                  '\'"\'"\'greedy\'"\'"\' --default-remote-prefix '
                  '\'"\'"\'snaketest/test1\'"\'"\' --default-remote-provider '
                  '\'"\'"\'AzBlob\'"\'"\' --default-resources '
                  '\'"\'"\'mem_mb=max(2*input.size_mb, 1000)\'"\'"\' '
                  '\'"\'"\'disk_mb=max(2*input.size_mb, 1000)\'"\'"\' '
                  '\'"\'"\'tmpdir=system_tmpdir\'"\'"\' --mode 2\'\'',
  'constraints': None,
  'container_settings': <azure.batch.models._models_py3.TaskContainerSettings object at 0x7f34f40c0990>,
  'depends_on': None,
  'display_name': None,
  'environment_settings': [ <azure.batch.models._models_py3.EnvironmentSetting object at 0x7f34ed4fe610>],
  'exit_conditions': None,
  'id': 'touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf',
  'multi_instance_settings': None,
  'output_files': None,
  'required_slots': None,
  'resource_files': [ <azure.batch.models._models_py3.ResourceFile object at 0x7f34f408bd10>],
  'user_identity': <azure.batch.models._models_py3.UserIdentity object at 0x7f34ed6b57d0>}
Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf: creation_time=2023-08-18 15:57:49.209008+00:00 state=TaskState.active node_info=None

Monitoring 1 active AzBatch tasks
task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf completed: result=TaskExecutionResult.success exit_code=0

task touch_text-faebc10e-3ddf-11ee-bceb-0022487978bf completed: run_time=0:00:01.213118, retry_count=0

Waiting at most 5 seconds for missing files.
Full Traceback (most recent call last):
  File "/data1/snakemake/snakemake/dag.py", line 606, in check_and_touch_output
    wait_for_files(
  File "/data1/snakemake/snakemake/io.py", line 881, in wait_for_files
    raise IOError(
OSError: Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
snaketest/test1/test.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/snakemake/snakemake/scheduler.py", line 613, in _finish_jobs
    self.get_executor(job).handle_job_success(job)
  File "/home/jake.vancampen@or.providence.org/data1/miniconda3/envs/snakemake/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/remote.py", line 235, in handle_job_success
    super().handle_job_success(
  File "/home/jake.vancampen@or.providence.org/data1/miniconda3/envs/snakemake/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/real.py", line 72, in handle_job_success
    job.postprocess(
  File "/data1/snakemake/snakemake/jobs.py", line 1189, in postprocess
    self.dag.check_and_touch_output(
  File "/data1/snakemake/snakemake/dag.py", line 613, in check_and_touch_output
    raise MissingOutputException(
snakemake.exceptions.MissingOutputException: Job 1  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
snaketest/test1/test.txt

MissingOutputException in rule touch_text in file /data1/eacri-snakemake-tutorial/test-small.smk, line 4:
Job 1  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
snaketest/test1/test.txt
  File "/home/jake.vancampen@or.providence.org/data1/miniconda3/envs/snakemake/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/remote.py", line 235, in handle_job_success
  File "/home/jake.vancampen@or.providence.org/data1/miniconda3/envs/snakemake/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/real.py", line 72, in handle_job_success
Cleanup job metadata.
Cleanup failed jobs output files.
Shutting down, this might take some time.
Deleting AzBatch job
Deleting AzBatch pool
Deleting workflow sources from blob
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-08-18T155745.063093.snakemake.log
unlocking
removing lock
removing lock
removed all locks
```

It seems like its waiting for the files on my local file system... id keep_remote different for the RemoteExecutor? Also the task succeeds on the node without actually running the rule ( the file was not generated remotely either ). Did the format_job_exec() change between the two executors ( Cluster and Remote ) ?

**Comment by vsoch** [comment]
@jakevc ok let's see - I'm not familiar with azure batch and I didn't work on that particular piece, but it looks like the changes are here: https://github.com/snakemake/snakemake/commit/c9eaa4e12e4a348f93e5ea5793faaec1fd547fac#diff-3a7c4d992c26b6767b554e11c830767fec6f1d798b3f3ddfa156a02839018f34 primarily using the classes provided here: https://github.com/snakemake/snakemake-interface-executor-plugins/blob/main/snakemake_interface_executor_plugins/executors/remote.py. The check seems to be happening for this other new class, the RealExecutor https://github.com/snakemake/snakemake-interface-executor-plugins/blob/main/snakemake_interface_executor_plugins/executors/real.py. 

This might be an overly simple suggestion - but it seems like the Azure Executor should still have a cluster executor type of base class. Did you try using any of the ClusterExecutor classes from the current version https://github.com/snakemake/snakemake/blob/main/snakemake/executors/__init__.py#L390 instead of RemoteExecutor?

**Comment by jakevc** [comment]
No this is a good suggestion I will try. In any case @johanneskoester is the goal to pull the Cluster Executor out entirely in favor of the `snakemake_interface_executor_plugins.executors.RemoteExecutor` ?

**Comment by vsoch** [comment]
@jakevc I can't answer for Johannes, but based on what I see in the current code, it looks like the ClusterExecutor is a kind of RemoteExecutor. So (regardless of where it is located, and indeed it could be an executor plugin itself) for the time being it's still in snakemake, and you will want to try using it!

> is the goal to pull the Cluster Executor out entirely in favor of the snakemake_interface_executor_plugins.executors.remote.RemoteExecutor ?

I don't think it would make sense to entirely remove the cluster executor and replace, since there are definitely cases where you want a RemoteExecutor that is not a ClusterExecutor (and vice versa). Just my opinion though!

**Comment by vsoch** [comment]
> I guess that's the issue I'm having though it that the snakemake.executors.ClusterExecutor was removed entirely [here](https://github.com/snakemake/snakemake/commit/c9eaa4e12e4a348f93e5ea5793faaec1fd547fac), a

Yes, but now it is represented here, no? https://github.com/snakemake/snakemake/blob/27b224ed12448df8aebc7d1ff8f25e3bf7622232/snakemake/executors/__init__.py#L390

> Maybe @johanneskoester would like the ClusterExecutor reimplemented in snakemake_interface_executor_plugins.executors ?

I think that's a possibility - we've discussed moving all of the executors to be external plugins. It could go there as a part of the external plugin _package_ that external executor plugins use, but it could also be an executor plugin itself - we haven't discussed design for executor plugins that depend on one another (but I suspect it would be fine to just have one be a Python dependency of another). But for your needs, right now, this won't be happening soon and you should try using the class I linked above. Is there something else that is holding you up, either for implementation or understanding?

**Comment by jakevc** [comment]
Okay I think I see what happened it looks like ClusterExecutor, and GenericClusterExecutor both existed in the code base at the same time back here: https://github.com/snakemake/snakemake/blob/78e6d6ec6a1ad930e40d6edfe9f7210232a674f2/snakemake/executors/__init__.py, 

I was using ClusterExecutor as the base class for AzBatchExecutor. 

Then what this commit did is actually to pull out ClusterExecutor and rename it RemoteExecutor and host those over in the interface plugins repo. So it's all good I guess I just need to fix the RemoteExecutor to remediate this issue that I am now seeing in the AzBatch Executor (that I have not quite diagnosed clearly yet).

**Comment by jakevc** [comment]
I have verified that the command line being submitted for my test job is the same before and after #2305 

The symptom I am experiencing is that the the task 'succeeds' on the batch node, but never actually runs, nothing is printed to stderr, stdout, no log files are generated. It's as if the `snakemake` command running on the node fails silently without even running the 'snakemake' command.

**Pull request closed without merging**
