### PR TITLE
Refactor f-strings

### PR DESCRIPTION
**Pull request by mbhall88**
Refactored some f-strings to restore python 3.5 compatibility.

### CODE REVIEW

**Comment by mbhall88** [comment]
I guess that given python 3.5 is now deprecated we might want to think about when we stop support (if we do)?

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thank you!

**Comment by johanneskoester** [comment]
We should probably also run the test suite with python 3.5. At least weekly or so.

**Comment by mbhall88** [comment]
> We should probably also run the test suite with python 3.5. At least weekly or so.

Looks like they still have it available in Actions, so should be pretty easy to add https://github.com/actions/python-versions/blob/17b1cd02cabff1d89e008c8356ecf41eb6f388de/versions-manifest.json#L1633

**Pull request merged**
