### PR TITLE
Added default remote provider support for Azure Storage

### PR DESCRIPTION
**Pull request by andreas-wilm**
Also implemented newly required `--az-configfile`. Argument is a JSON/YAML file that holds variables used for CloudStorageAccount in AzureStorage.RemoteProvider. Credentials here means key/value pairs that work with [Azure's CloudStorageAccount](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/cloudstorageaccount.py), e.g. `account_name` (storage account name) and either `sas_token` (no leading '?') or `account_key`.

This PR doesn't contain updated documentation yet, but I'm putting it out here, so that others can test it first.

See also https://github.com/snakemake/snakemake/issues/57

### CODE REVIEW

**Comment by andreas-wilm** [comment]
I should have added that I introduced a config file argument, because 1) previously the AZ storage authentication was done through env vars only and 2) we need a config file anyway for later AZ batch integration

**Comment by andreas-wilm** [comment]
Note above change from --az-configfile to --az-store-credentials when testing

**Comment by andreas-wilm** [comment]
Please don't merge until env vars are supported here

**Comment by andreas-wilm** [comment]
Reworked this PR 

- Az Blob now uses env vars "AZ_ACCOUNT_NAME", "AZ_ACCOUNT_KEY" and "AZ_SAS_TOKEN" automatically for AzBlob authentication
- Updated docs
- renamed AzureStorage AzBlob (but kept support for old naming)
- removed previously introduced az-credentials

Better to resubmit as new PR?

**Comment by andreas-wilm** [comment]
Also noticed time sync issues after the push

**Comment by johanneskoester** [comment]
Can you format with black?

**Comment by andreas-wilm** [comment]
Will format with black

Let me also fix one more tiny bug before merging (will post update here)

**Comment by andreas-wilm** [comment]
Formatted with black. Tiny bug triggered by missing AZ vars fixed. Good to merge

**Comment by andreas-wilm** [comment]
Note, this PR renames remote/AzureStorage.py to remote/AzBlob.py. The docs are updated accordingly.

**Comment by andreas-wilm** [comment]
Don't merge yet. The azure-storage has just (12th May) been deprecated in favour of azure-storage-blob.

**Comment by andreas-wilm** [comment]
Now using the newer azure-storage-blob. All tests successful (blob with local execution and Kubernetes)

**Comment by andreas-wilm** [comment]
Blog post https://andreas-wilm.github.io/2020-06-08-snakemake-on-ask/

**Comment by andreas-wilm** [comment]
Added AKS tutorial as found [on my blog](https://andreas-wilm.github.io/2020-06-08-snakemake-on-ask/). Couldn't get the entire documentation to render, so only checked with Pandoc, i.e. this might need some polishing

**Pull request merged**
