### PR TITLE
feat: added localrule directive

### LINKED ISSUE #945: Localrules not compatible with new module mechanism
**Snakemake version**
6.1.1

**Describe the bug**
Rules defined as ``localrules`` aren't localrules anymore when imported from a module. 

**Logs**
```bash
localrules directive specifies rules that are not present in the Snakefile:
	a
```

**Minimal example**
```Python
# module.smk

localrules: a

rule a:
    output: "something.txt"
    shell: "touch {output}"

rule b:
    input: rules.a.output
    output: "another.txt"
    shell: "touch {output}"

# Snakefile

module other_workflow:
    snakefile: "module.smk"

use rule * from other_workflow as other_*
```

### PR DESCRIPTION
**Pull request by fgvieira**
### Description

Added support for rule directive `localrule`, as described in #1591 and to fix #945.

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Review by johanneskoester — APPROVED** [review]

**Comment by corneliusroemer** [comment]
Does this require changes in snakefmt @mbhall88?

**Comment by mbhall88** [comment]
> Does this require changes in snakefmt @mbhall88?

Yes it will.

**Comment by corneliusroemer** [comment]
@johanneskoester would be great if you pinged snakefmt if something requires changes - I just stumbled over this when reading through changelog, which I don't always do. Would be good to be proactively ping so that changes are ready when the version comes out.

**Comment by mbhall88** [comment]
@corneliusroemer we would have detected it next time we update the minimum pin for the snakemake (dev) dependency. We have a test that checks that all ruleparams etc. are covered by snakefmt.

**Pull request merged**
