### PR TITLE
fix: issue with duplicated prefix for checkpoints on cloud

### LINKED ISSUE #574: default remote prefix duplicated for checkpoint output on cloud
**Snakemake version**
5.22.1

**Describe the bug**
Using the `--default-remote-prefix` parameter will cause `MissingInputException` errors to arise for the outputs of checkpoint rules.

**Steps to Reproduce**
Follow the [Google Life Sciences Executor Tutorial](https://snakemake.readthedocs.io/en/stable/executor_tutorial/google_lifesciences.html) but convert the `bwa_map` rule into a checkpoint like this
```
diff --git Snakefile Snakefile
index 68974d1..d519d4f 100644
--- Snakefile
+++ Snakefile
@@ -4,7 +4,7 @@ rule all:
     input:
         "plots/quals.svg"

-rule bwa_map:
+checkpoint bwa_map:
     input:
         fastq="samples/{sample}.fastq",
         idx=multiext("genome.fa", ".amb", ".ann", ".bwt", ".pac", ".sa")
@@ -19,7 +19,7 @@ rule bwa_map:

 rule samtools_sort:
     input:
-        "mapped_reads/{sample}.bam"
+        lambda wildcards: checkpoints.bwa_map.get(sample=wildcards.sample).output[0]
     output:
         "sorted_reads/{sample}.bam"
     conda:
```
and then you should see the following when running the pipeline:
```
Building DAG of jobs...
MissingInputException in line 20 of Snakefile:
Missing input files for rule samtools_sort:
snakemake-testing-data/snakemake-testing-data/mapped_reads/A.bam
```
Notice how `snakemake-testing-data` appears prepended twice?

**Bug Hypothesis**
I think `rules.apply_default_remote()` is being applied to the output more than once. It might help to check whether `incomplete` is true [on this line](https://github.com/snakemake/snakemake/blob/7481db14d93b73d6c0aeb8e42f3dc510019c48e4/snakemake/rules.py#L721) before executing `rules.apply_default_remote()`?

It might be possible that this is a bug that extends beyond the life sciences executor (to other cloud environments), but I haven't tested that yet.

### PR DESCRIPTION
**Pull request by aryarm**
Implements a test to reproduce issue #574: checkpoints in cloud execution mode.

Note: this PR duplicates #1199.

Once I'm able to reproduce the issue, I'm planning on using this PR to fix it.

**Update (1/14/22)**: This PR now also resolves #574
See https://github.com/snakemake/snakemake/issues/574#issuecomment-702274567 for a description of the bug and the solution that I implemented.

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by aryarm** [comment]
nice! it looks like the test failed properly

I should have some time next week to try some fixes.

**Comment by johanneskoester** [comment]
Thanks a lot for giving this a try!!

**Comment by aryarm** [comment]
@johanneskoester, it's ready for you to take a look!

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thanks a lot for fixing this long standing bug!

**Pull request merged**
