### PR TITLE
feat: add tes token

### PR DESCRIPTION
**Pull request by svedziok**
### Description

This PR adds a parameter for forwarding a JWT to a TES instance for authentication.

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Thanks! One thing: when configuring like this, the token ends up in the shell history. I think it is better to use an environment variable for this instead of a CLI arg. Is there a default env var used in TES implementations already? If not we could name it just TES_TOKEN?

**Comment by svedziok** [comment]
> Thanks! One thing: when configuring like this, the token ends up in the shell history. I think it is better to use an environment variable for this instead of a CLI arg. Is there a default env var used in TES implementations already? If not we could name it just TES_TOKEN?

Hi Johannses, thanks for the review. Do you think, using env vars is required? Using an arg was in accordance to cwl-tes (see here: https://github.com/ohsu-comp-bio/cwl-tes). We also do not see a big security risk as the tokens' validity is generally short. E.g. in WESkit we document arguments as well as env vars that are set by the users anyhow.

**Comment by johanneskoester** [comment]
Mhm, I think an env var is indeed better here. Also, it can be more convenient because it can be set without needing to tell it to Snakemake upon each invocation.

**Comment by svedziok** [comment]
> Thanks! One thing: when configuring like this, the token ends up in the shell history. I think it is better to use an environment variable for this instead of a CLI arg. Is there a default env var used in TES implementations already? If not we could name it just TES_TOKEN?

solved - added env var and documentation

**Comment by svedziok** [comment]
@johanneskoester all is resolved - can we merge now?

**Comment by svedziok** [comment]
> Mhm, I think an env var is indeed better here. Also, it can be more convenient because it can be set without needing to tell it to Snakemake upon each invocation.

done

**Comment by svedziok** [comment]
> Thanks! One thing: when configuring like this, the token ends up in the shell history. I think it is better to use an environment variable for this instead of a CLI arg. Is there a default env var used in TES implementations already? If not we could name it just TES_TOKEN?

done

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thanks a lot!

**Pull request merged**
