### PR TITLE
PEP support via peppy and eido.

### PR DESCRIPTION
**Pull request by johanneskoester**
This PR introduces support for [PEPs](http://pep.databio.org) as a way of configuring a workflow.
Integration works by simply writing

```
pepfile: "pep/config.yaml"
pepschema: "workflow/schemas/pep.yaml"
```

### TODO

* [x] add eido and peppy to conda-forge
* [x] add testcase
* [x] add docs

### CODE REVIEW

**Comment by johanneskoester** [comment]
cc @nsheff

**Comment by nsheff** [comment]
Hi, looks great -- anything you need from me?

**Comment by nsheff** [comment]
cc @vreuter and @stolarczyk

**Comment by nsheff** [comment]
eido and peppy are now on conda-forge as requested.

https://anaconda.org/conda-forge/eido

https://anaconda.org/conda-forge/peppy

**Comment by nsheff** [comment]
Hi Johannes, just wanted to check in on this and see what you think

**Comment by johanneskoester** [comment]
Finally done @nsheff. Once tests pass, I'll merge this.

**Pull request merged**
