### PR TITLE
Fix issue #817: assign job id if it doesn't exist in DAG.jobid()

### PR DESCRIPTION
**Pull request by jmeppley**
This simple fix solves #817, but it may break the jobid consistency created by 71b5aeb35b0919f906189d5a945a7d7e189ed90e. I suspect undoing that commit would also solve this bug.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Thanks a lot for pointing me to this issue! The jobid information during the checkpoint update is not so important, hence I think it is simpler and faster to just omit it. Closing in favor of #839.

**Comment by epruesse** [comment]
This may yet be needed. While I was trying to come up with an MWE for #855 I managed to trigger the key error. If you have two rules using the same checkpoint and directly depending on one another, there is an update/replace_job before the job is created.

**Comment by jbloom** [comment]
I am getting this error too in a complicated workflow where the same checkpoint is being referred to multiple times. I don't really understand the error or all the discussion above, but I'm getting it in 5.32.1 which makes me suspect @epruesse is correct and it's not fixed by @johanneskoester's #839:
```
snakemake/dag.py", line 700, in jobid
    return self._jobid[job]
KeyError
```

**Comment by epruesse** [comment]
@jbloom - Can you come up with an MWE and open a new issue?

**Pull request closed without merging**
