### PR TITLE
fix #732: allow wildcards in notebook path

### LINKED ISSUE #732: Wildcards in notebook path do not work
Hi, I cannot run notebooks with wildcards in their name.
Is there a way to fix this fast?
I really need it.

**Snakemake version**
v5.27.4 from conda

**Describe the bug**
Having wildcards in the notebook path does not work

**Logs**
```
RuleException:
KeyError in line 10 of /data/nasif12/home_if12/hoelzlwi/tmp/snakemake_test/Snakefile:
'wildcards'
  File "/opt/modules/i12g/anaconda/envs/asdf/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2252, in run_wrapper
  File "/data/nasif12/home_if12/hoelzlwi/tmp/snakemake_test/Snakefile", line 10, in __rule_test
  File "/opt/modules/i12g/anaconda/envs/asdf/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/opt/modules/i12g/anaconda/envs/asdf/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/opt/modules/i12g/anaconda/envs/asdf/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/opt/modules/i12g/anaconda/envs/asdf/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2264, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data/nasif12/home_if12/asdf/tmp/snakemake_test/.snakemake/log/2020-11-06T185315.421804.snakemake.log
```

**Minimal example**
```
rule all:
  input:
    "asdf.txt"

rule test:
  output:
    "{name}.txt"
  input:
  notebook:
    "{name}.ipynb"
```

### PR DESCRIPTION
**Pull request by Hoeze**
This is my approach to fix https://github.com/snakemake/snakemake/issues/732

### CODE REVIEW

**Comment by Hoeze** [comment]
@johanneskoester Do you know why formatting fails here?

**Comment by johanneskoester** [comment]
You need to format with latest black (20.x).

**Review by johanneskoester — CHANGES_REQUESTED** [review]
From the TODO above your change you see that this has some issues. If we enable it, the test case also has to include a check for the same with the script directive, as well as a test for snakemake --report.

**Comment by Hoeze** [comment]
@johanneskoester thanks for the hint to run black.
Tests pass now.

However, I could not find any TODO. 
In case there are still changes needed, would you mind pointing me to the actual source code that I have to adapt?

**Comment by johanneskoester** [comment]
Is this feature documented anywhere? I had in mind that it is just hidden at the moment...

**Comment by johanneskoester** [comment]
Anyway, I am having a look at it now, give me some minutes.

**Comment by johanneskoester** [comment]
Ok, done, closing in favor of #740. Thanks a lot for pointing me to the issue and the initial fix!

**Pull request closed without merging**
