### PR TITLE
feat: add --sdm short opt for --deployment

### PR DESCRIPTION
**Pull request by mbhall88**
### Description

The new `--software-deployment-method`/`--deployment-method`/`--deployment` is probably a heavily used option for most users, so I think it would benefit from a shorthand option as it is quite verbose. Seems `-m` is available and is kind of related.

I've also updated the docs with some references to this shorthand version and replaced some longform usage with the short option, ensuring it is made clear what the shorthand option is an alias for. Happy to change this though.

### QC

* [ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by johanneskoester** [comment]
Good idea, but I think I would prefer `--sdm` instead (instead of a single letter code). THis way, it should be easier to remember and decipher.

**Comment by mbhall88** [comment]
> Good idea, but I think I would prefer `--sdm` instead (instead of a single letter code). THis way, it should be easier to remember and decipher.

Done

**Comment by mbhall88** [comment]
@johanneskoester i didn’t really touch any code so I don’t know why test are failing…

**Comment by mbhall88** [comment]
Ah it was because when I went from `-m` to `--sdm` it renames the option to `args.sdm` rather than `args.software_deployment_method`

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
