### PR TITLE
Implement Paramspace helper and testcase.

### PR DESCRIPTION
**Pull request by johanneskoester**
This is inspired by the work on JUDI from @soumitrakp. Thanks a lot Soumitra!
Key idea:
Snakemake already brings everything to handle parameter spaces in any way (sub-spacing for certain rules and even depending on wildcard values, the ability to read or generate spaces on the fly or from files via pandas, etc. However, there was so far no easy way to translate a space into wildcard patterns, and translate it back into concrete parameters for scripts and commands. This is now solved via the new `Paramspace` helper, which can be used as follows:

```python
from snakemake.utils import Paramspace
import pandas as pd

# declare a dataframe to be a paramspace
paramspace = Paramspace(pd.read_csv("params.tsv", sep="\t"))


rule all:
    input:
        # Aggregate over entire parameter space (or a subset thereof if needed)
        # of course, something like this can happen anywhere in the workflow (not 
        # only at the end).
        expand("results/plots/{params}.pdf", params=paramspace.instance_patterns)


rule simulate:
    output:
        # format a wildcard pattern like "alpha~{alpha}/beta~{beta}/gamma~{gamma}" 
        # into a file path, with alpha, beta, gamma being the columns of the data frame
        f"results/simulations/{paramspace.wildcard_pattern}.tsv"
    params:
        # automatically translate the wildcard values into an instance of the param space
        # in the form of a dict (here: {"alpha": ..., "beta": ..., "gamma": ...})
        simulation=paramspace.instance
    script:
        "scripts/simulate.py"


rule plot:
    input:
        f"results/simulations/{paramspace.wildcard_pattern}.tsv"
    output:
        f"results/plots/{paramspace.wildcard_pattern}.pdf"
    shell:
        "touch {output}"
```

Given that `params.tsv` contains:
```
alpha	beta	gamma
1.0	0.1	0.99
2.0	0.0	3.9
```

This workflow will run as follows:
```
[Fri Nov 27 20:57:27 2020]
rule simulate:
    output: results/simulations/alpha~2.0/beta~0.0/gamma~3.9.tsv                                                                                                                           
    jobid: 4                                                                                                                                                                               
    wildcards: alpha=2.0, beta=0.0, gamma=3.9                                                                                                                                              

[Fri Nov 27 20:57:27 2020]
rule simulate:
    output: results/simulations/alpha~1.0/beta~0.1/gamma~0.99.tsv                                                                                                                          
    jobid: 2                                                                                                                                                                               
    wildcards: alpha=1.0, beta=0.1, gamma=0.99                                                                                                                                             

[Fri Nov 27 20:57:27 2020]
rule plot:
    input: results/simulations/alpha~2.0/beta~0.0/gamma~3.9.tsv                                                                                                                            
    output: results/plots/alpha~2.0/beta~0.0/gamma~3.9.pdf                                                                                                                                 
    jobid: 3                                                                                                                                                                               
    wildcards: alpha=2.0, beta=0.0, gamma=3.9                                                                                                                                              


[Fri Nov 27 20:57:27 2020]
rule plot:
    input: results/simulations/alpha~1.0/beta~0.1/gamma~0.99.tsv                                                                                                                           
    output: results/plots/alpha~1.0/beta~0.1/gamma~0.99.pdf                                                                                                                                
    jobid: 1                                                                                                                                                                               
    wildcards: alpha=1.0, beta=0.1, gamma=0.99                                                                                                                                             


[Fri Nov 27 20:57:27 2020]
localrule all:
    input: results/plots/alpha~1.0/beta~0.1/gamma~0.99.pdf, results/plots/alpha~2.0/beta~0.0/gamma~3.9.pdf                                                                                 
    jobid: 0
```

### CODE REVIEW

**Comment by HenningTimm** [comment]
This is a really cool feature that is going to make at least one of my workflows a lot easier to read and maintain. Thank you :)

The pattern is currently restricted to create a new directory level for each parameter, right? This could lead to very deep folder structures that might be inconvenient to work with. From a [data management standpoint](https://library.ucsd.edu/research-and-collections/data-curation/best-practices.html) it might be helpful to group some parameters into the filename, specifically for human readability and to maintain metadata in case a file is moved.

Would/ could/ should there be a way to pass a custom pattern to `Paramspace` to override this (reasonable) default behavior? Another option could be to add annotations to the parameter file grouping parameters into directory and file name parameters.

**Comment by HenningTimm** [comment]
I implemented a version of this allowing to pass custom patterns while keeping the default behavior intact. Please consider this a first draft/ proposition. If this runs contrary to your goal for this, feel free to ignore this.

This example uses the pattern "{}/{}_{}" which groups the latter two parameters (beta and gamma) into one file name.
```
from snakemake.utils import Paramspace
import pandas as pd

# Add the pattern here
paramspace = Paramspace(pd.read_csv("params.tsv", sep="\t"), pattern="{}/{}_{}")

rule all:
    input:
        expand("results/plots/{params}.pdf", params=paramspace.instance_patterns)

# rest as above
# [...]
```

This results in the following paths:
```
[Sun Dec  6 18:46:11 2020]
rule simulate:
    output: results/simulations/alpha~2.0/beta~0.0_gamma~3.9.tsv
    jobid: 4
    wildcards: alpha=2.0, beta=0.0, gamma=3.9

[Sun Dec  6 18:46:11 2020]
rule simulate:
    output: results/simulations/alpha~1.0/beta~0.1_gamma~0.99.tsv
    jobid: 2
    wildcards: alpha=1.0, beta=0.1, gamma=0.99

[Sun Dec  6 18:46:11 2020]
rule plot:
    input: results/simulations/alpha~1.0/beta~0.1_gamma~0.99.tsv
    output: results/plots/alpha~1.0/beta~0.1_gamma~0.99.pdf
    jobid: 1
    wildcards: alpha=1.0, beta=0.1, gamma=0.99

[Sun Dec  6 18:46:11 2020]
rule plot:
    input: results/simulations/alpha~2.0/beta~0.0_gamma~3.9.tsv
    output: results/plots/alpha~2.0/beta~0.0_gamma~3.9.pdf
    jobid: 3
    wildcards: alpha=2.0, beta=0.0, gamma=3.9

[Sun Dec  6 18:46:11 2020]
localrule all:
    input: results/plots/alpha~1.0/beta~0.1_gamma~0.99.pdf, results/plots/alpha~2.0/beta~0.0_gamma~3.9.pdf
    jobid: 0
```

**Comment by soumitrakp** [comment]
Hi Henning,
Could you please have a look at the discussion here:
https://twitter.com/johanneskoester/status/1332423263251795968
Thank you,
Soumitra

**Comment by johanneskoester** [comment]
> I implemented a version of this allowing to pass custom patterns while keeping the default behavior intact. I hope I managed to direct my PR against this branch successfully ;) Please consider this a first draft/ proposition. If this runs contrary to your goal for this, feel free to ignore this.
> 
> This example uses the pattern "{}/{}_{}" which groups the latter two parameters (beta and gamma) into one file name.
> 
> ```
> from snakemake.utils import Paramspace
> import pandas as pd
> 
> # Add the pattern here
> paramspace = Paramspace(pd.read_csv("params.tsv", sep="\t"), pattern="{}/{}_{}")
> 
> rule all:
>     input:
>         expand("results/plots/{params}.pdf", params=paramspace.instance_patterns)
> 
> # rest as above
> # [...]
> ```
> 
> This results in the following paths:
> 
> ```
> [Sun Dec  6 18:46:11 2020]
> rule simulate:
>     output: results/simulations/alpha~2.0/beta~0.0_gamma~3.9.tsv
>     jobid: 4
>     wildcards: alpha=2.0, beta=0.0, gamma=3.9
> 
> [Sun Dec  6 18:46:11 2020]
> rule simulate:
>     output: results/simulations/alpha~1.0/beta~0.1_gamma~0.99.tsv
>     jobid: 2
>     wildcards: alpha=1.0, beta=0.1, gamma=0.99
> 
> [Sun Dec  6 18:46:11 2020]
> rule plot:
>     input: results/simulations/alpha~1.0/beta~0.1_gamma~0.99.tsv
>     output: results/plots/alpha~1.0/beta~0.1_gamma~0.99.pdf
>     jobid: 1
>     wildcards: alpha=1.0, beta=0.1, gamma=0.99
> 
> [Sun Dec  6 18:46:11 2020]
> rule plot:
>     input: results/simulations/alpha~2.0/beta~0.0_gamma~3.9.tsv
>     output: results/plots/alpha~2.0/beta~0.0_gamma~3.9.pdf
>     jobid: 3
>     wildcards: alpha=2.0, beta=0.0, gamma=3.9
> 
> [Sun Dec  6 18:46:11 2020]
> localrule all:
>     input: results/plots/alpha~1.0/beta~0.1_gamma~0.99.pdf, results/plots/alpha~2.0/beta~0.0_gamma~3.9.pdf
>     jobid: 0
> ```

very good suggestion! Only one thing: the pattern should probably contain the names. That would be more in line with the rest of Snakemake.

**Pull request merged**
