### PR TITLE
bugfix for issue #413: stop using realpath when looking for nested output paths

### PR DESCRIPTION
**Pull request by jmeppley**
I think the use of os.path.realpath does nothing for us when checking for outputs that are children of each other. It has no effect before the outputs exist, and I don't think we want different behavior here after the outputs exist. I also don't see the benefit of resolving links for this, but maybe I'm missing something.

Assuming it can be safely removed, then its removal solves issue #413.

### CODE REVIEW

**Comment by tbooth** [comment]
I've also been affected by this issue and the fix here looks reasonable to me. It may still be possible to induce unexpected behaviour by making symlinks to directories, but I think anyone who's doing that gets what they deserve.

**Comment by alienzj** [comment]
Very useful, merge please.

**Comment by twrightsman** [comment]
This issue has also been affecting my workflows. A typical usecase is having additional processing steps for one type of files but skipping those in another. If a file skips this processing step I'll just symlink it to the output of the processing step. Patching the changes in this PR fixes my DAG resolution issues doing this.

**Comment by tbooth** [comment]
Hi, Just another plea to consider merging this fix or equivalent ASAP. I'm having to apply this patch every time after updating Snakemake or else my workflows break.

**Comment by VGalata** [comment]
Another plea to review this patch.

**Comment by jmeppley** [comment]
My first test wouldn't work without altering tests.common.run to fix the no_tmpdir flag. (At least I thought it was a fix). But that seems to have broken at least one windows test.

I've created a new PR (#825) with this fix that should pass all the tests.

**Pull request closed without merging**
