### PR TITLE
fix: Improved handling of missing output files in group job postprocessing, accounting for temporary files.

### PR DESCRIPTION
**Pull request by pvandyken**
When I run group jobs on a cluster, I'll often write temporary files to the node-specific local scratch folder. I'll label them `temp(...)` and the sub-snakemake instance will dutifully delete the files when no longer needed. Even without that deletion, the files would disappear with the node local scratch as soon as the group job finishes.

The problem occurs when the parent snakemake instance re-assumes control. It checks for all the outputs from the group job, finds the temp files missing, and exits with an error. But these temp files are no longer needed anywhere in the workflow, and indeed, Snakemake's immediate next step if it were to find the temp files would be to delete them.

This PR filters the group job outputs before the existence checks, removing any that are:
- Not needed anywhere else in the workflow
- Not target files

In particular, only files that would otherwise be immediately removed are excluded from the existence check (at least, that's the idea).

The idea is to remove a small frustration without causing any breaking or generally noticeable changes. I've no test yet, but I'll write one if the concept here is approved.

### QC

* [ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

## Summary by CodeRabbit

- **New Features**
	- Enhanced output checking mechanism to selectively ignore specific output files.
	- Improved handling of missing output files in job postprocessing, accounting for temporary files.

- **Bug Fixes**
	- Refined logic for determining if files are needed by pending jobs, improving accuracy in output management.

### CODE REVIEW

**Comment by DrYak** [comment]
This looks nice because it also solves a feature I would have liked to have: #1474 

It solves the whole "_files that only live for the duration of the group running on the node_" part of the problem.

**Comment by pvandyken** [comment]
One clarification: sub-snakemake instances on the cluster actually do **not** automatically delete the temp files (they get called with `--notemp`). This behaviour is fine, it just means this PR more specifically deals with temp files automatically deleted by the cluster off of local scratch. I don't think this will have any effect on temp files not saved on local scratch (i.e. they should be deleted as normal after the group job finishes), but I'll do some more specific investigations on this at some point.

**Comment by DrYak** [comment]
@pvandyken : Yes, I meant that we could start also storing our on node-local scratch, completely aleviating all problems of file that don't even live beyond group job.

We're currently testing this on our production server. (:notes: Living on the edge!  :guitar: :man_singer:)

**Comment by pvandyken** [comment]
@DrYak Ah, no worries, I was clarifying myself because I made a mistake in the initial post. I wanted to correct it for the record.

**Comment by john-hen** [comment]
@DrYak Actually, what we're currently testing on our production server (with a "hot patch", as it hasn't been merged yet), is #1779.

**Review by johanneskoester — APPROVED** [review]

**Comment by pvandyken** [comment]
@johanneskoester thanks for merging!

**Pull request merged**
