### PR TITLE
Fix windows test suite and enable Windows test CI

### PR DESCRIPTION
**Pull request by melund**
I reopening the PR from Bitbucket on fixing the test suite on windows. 

I have enabled Windows CI tests on Github actions.  

Orginal discription from bitbucket: 
---------------------------------------

This PR fixes the test suite for Windows. From a a handful of passed tests to 97 passed and 53 skipped.

This is done by fixing the some actual Windows issues and skipping tests for features which can’t work on Windows. (Many windows fixes where done i separate PRs on bitbucket which have already been merged) 

Most of the tests rely on bash to work, which is a problem on Windows were "cmd.exe" is the default shell. So this PR implements a new option in the shell class to use bash as external executable on Windows. It adds a simi hidden ``shell.use_bash_on_win(bashcmd)`` convenience function to easily configure bash. If `bashcmd` is `None` it will try to locate a bash from either a conda installed git or from system installed "git for windows".

In some tests the expected files on Windows will be different. To handle this, a new option is added which allows for Windows specific expected files in the test setup. If files in the "expected-results" folder are postfix'ed with "_WIN" they will be used instead of the non postfixed files.

It also adds an option to the test-framework to ignore line endings when comparing output files on Windows. Controlling line endings on Windows is a pain.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Thanks! I will have a look at this once I have moved the tests from circle CI to Github actions. Then, I will also enable windows tests and we can directly see the effects.

**Comment by melund** [comment]
Awesome. I have updated the branch and fixed test regression since I last looked at this. 

I also included a azzure pipeline configuration if you want to activate CI now. But I think GitHub actions are probably better in the long run. 

There are a few generic changes in this PR which you could lift when fixing tests. For example a fixture which resets `sys.path` between tests.

**Comment by melund** [comment]
I fixed a small typo that broke named pipes on Posix. So now tests pass on posix again :)

 I have also removed the the azure pipeline definition file since github actions is probably the best option. If you need it here is a link:
[azure-pipelines.yml.txt](https://github.com/snakemake/snakemake/files/3728512/azure-pipelines.yml.txt)

I haven't tried Github actions so I can't help much there. However, can't wait to see it in action

**Comment by melund** [comment]
@johanneskoester Tests on Github actions fails in a place I haven't seen before ([test_convert_to_cwl](https://github.com/snakemake/snakemake/pull/19/checks?check_run_id=267258094#step:8:185)). Do you my PR caused the failure or is it expected with the new github action tests?

**Comment by melund** [comment]
Wait. Why doesn't the GitHub actions workflow start now... That is really odd.

**Comment by melund** [comment]
Maybe something is wrong with Github actions right now.

**Comment by melund** [comment]
Hurray. Now the [windows tests suite passes](https://github.com/snakemake/snakemake/pull/19/checks?check_run_id=277547301#step:6:206) :cake: 🌟 🎈 
```
== 97 passed, 53 skipped, 1 xfailed, 1 xpassed, 10 warnings in 31.16 seconds ==
```

Check #59 for a reference on how the test suite did on Windows before. 

@johanneskoester This is ready for to be reviewed.

**Comment by melund** [comment]
I better merge master in again and check that the test suite still works on Windows :)

**Comment by melund** [comment]
@johanneskoester Any plans for when you want to integrate this? 

Current state requires me to update/check the windows test suite manually every time something else is merged to master.

**Comment by melund** [comment]
@johanneskoester Any chance that this can go anytime this winter? Then I will plan to spend a bit of time to rebase it again and update the tests.

**Comment by melund** [comment]
@johanneskoester Rebasing is very time consuming this time. A lot of things have been restructured, and a few new things are just incompatible with windows. For example the hack of using `urllib.parse` for detecting if a file is local or not. That doesn't work for absolute paths on windows. 

I don't mind to trying to fix this again. But only if you are actually going to integrate it and enable CI testing for windows. Otherwise this is a waste of time.

**Comment by melund** [comment]
I have reopen this PR from a local branch instead of my fork. #222

**Pull request closed without merging**
