### PR TITLE
Paramspace patterns

### PR DESCRIPTION
**Pull request by HenningTimm**
This PR adds a parameter allowing custom patterns to the Paramspace class implemented in #776 
A string formatting pattern like `"{}/{}_{}"` can be passed to achieve different connections between parameter values. This allows for shallower directory structures when many parameters are used.
Currently, in this PR there is no verification that the supplied pattern contains the right number of formatting fields. Too many format fields result in `IndexError: tuple index out of range`, but too few fields could go unnoticed. 

The only solid way to achieve this that I could come up with would be adding the following steps to the `__init__`:
1. Try to format the pattern string using an amount of dummy values equal to the number of supplied params. If this fails, raise an error since there are too few params.
2. Try to format the pattern string using exactly one dummy parameter less than before. If this fails, the expected amount of format fields was supplied and everything is ok. If this formatting works, there were too many parameters: Raise an error.

An easier solution would be to count the number of opening and closing curly braces. However, this fails to properly report the number of fields for patterns that contain escaped curly braces. While I would consider this to be an unlikely case, using this approach could lead to arcane and hard to debug errors.

### CODE REVIEW

**Comment by johanneskoester** [comment]
As mentioned in the other PR, can we make the placeholders in the pattern named instead of plain `{}` placeholders?

**Comment by johanneskoester** [comment]
On the other hand, if there are many columns it can be cumbersome to specify the whole pattern, and even impossible to do so. Maybe it is better to just offer
```
Paramspace(df, filename_params=["alpha", "beta"])
```
and if filename_params is None, Paramspace will just use the last column for the filename?

**Comment by HenningTimm** [comment]
Worked on a first draft of this that seems to work. Tests etc. are still missing.

**Comment by HenningTimm** [comment]
The last commits add a parameter to select the symbol used to join the parameter name and value. The default remains `'~'`. There are currently some errors, but since they also occurred on the main branch, I am confident that this code is not to blame ;)

Testing locally I observed the inverse problem: The test cases I wrote finished without issue even though the generated files did not match the structure in `expected-results`. Maybe I am doing something wrong there.

**Comment by johanneskoester** [comment]
Can you merge in latest master from upstream?

**Comment by HenningTimm** [comment]
Thank you, that solved the test errors. I still need to add a test for the join string parameter before this is ready to merge.

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
@HenningTimm any chance to get the final testcase today? And a merge with upstream master? I have already included paramspace into the paper, and hope it to appear online soon.

**Comment by HenningTimm** [comment]
@johanneskoester  OK, no problem. I will get this done today.

**Comment by HenningTimm** [comment]
@johanneskoester Everything runs as intended now and the test seem to work. However, the comparison with the content of the "expected-results" folder does not seem to work. I will open a new PR for that.

**Pull request merged**
