### PR TITLE
fix: parsing fstring with if else on params #2657

### PR DESCRIPTION
**Pull request by sravel**
fix:  parsing fstring with if else on params #2657

### QC

* [ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
May I ask you to add a testcase?

**Comment by sravel** [comment]
Hello I don't now how can do that, I open issue since 4 months and just to need fix to switch my workflow on snakemake 8....

**Comment by tedil** [comment]
Hi @sravel I've modified the code to use tokenize.LBRACE/RBRACE and added a testcase which makes use of f-strings (and should simply error when parsing goes awry). Is that okay with you?

**Comment by johanneskoester** [comment]
Fixed already and test included by PR https://github.com/snakemake/snakemake/pull/2930

**Comment by johanneskoester** [comment]
Nevertheless, thanks a lot for helping with this!!

**Pull request closed without merging**
