### PR TITLE
fix: Use 'snakemake.utils.update_config' instead of 'dict.update'

### PR DESCRIPTION
**Pull request by kpj**
### Description

When merging configs, Snakemake uses `dict.update` instead of `snakemake.utils.update_config` which is not recursive.
Nested config options can thus disappear unexpectedly.

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by kpj** [comment]
@johanneskoester Any thoughts on this? :-)

**Comment by johanneskoester** [comment]
Soemthing fails on windows now. Do you have a clue?

**Comment by johanneskoester** [comment]
Thanks a lot, finally done :-).

**Comment by kpj** [comment]
Wonderful! Thanks a lot for the debugging as well :-)

**Pull request merged**
