### PR TITLE
fix: require python >=3.7 again (the python 3.9 dependency was unnecessary)

### PR DESCRIPTION
**Pull request by dlaehnemann**
### Description

The respective bug was introduced with PR #2341, so it exists starting with version `7.30.2`. Also see issue #2369 and PR #2370 for further context.

This code from PR #2341 seems to get run every time a conda environment is used:

https://github.com/snakemake/snakemake/blob/13b5d4d11d7475f942531c51b6013962a88a72b7/snakemake/__init__.py#L8-L9

Thus, any conda environment in a rule with an older python version included, will trigger a:
```
  File "/opt/conda/envs/snakemake/lib/python3.11/site-packages/snakemake/__init__.py", line 9, in <module>
    raise ValueError("Snakemake requires at least Python 3.9.")
ValueError: Snakemake requires at least Python 3.9.
```

This would preclude snakemake from running any software that needs an older python version, so this is clearly an unwanted side-effect. But I am not sure how to fix this.

Currently, this PR is only a minimal example test to trigger this behaviour in the CI tests. Hopefully, this will make debugging it quicker for @johanneskoester (or someone else?).

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by dlaehnemann** [comment]
A quick workaround for anybody getting this bug, until it is fixed: Downgrade your `snakemake` to `<=7.30.1`.

**Comment by dlaehnemann** [comment]
So, this bug gets triggered in the Windows CI already, right here is the actual error message:
https://github.com/snakemake/snakemake/actions/runs/5690154966/job/15423010580?pr=2372#step:6:526

Currently rerunning the Linux CI, as this failed on slurm cluster creation earlier in the tests.

**Comment by dlaehnemann** [comment]
The Linux CI failure seem to be an unrelated and obscure error, where the general GitHub Actions runner is `Ubuntu 22.04.2`, but the slurm setup tries to download `Ubuntu 22.04.1` packages, with the respective version not available on the Azure Ubuntu package mirror. I have no clue, why these versions would be out of sync...

**Comment by dlaehnemann** [comment]
Here's a related PR for the Linux CI failure with the slurm setup #2377 .

**Comment by johanneskoester** [comment]
I expect this to be fixed with the changes in https://github.com/snakemake/snakemake/pull/2305. However, that will become Snakemake 8.0. I'll think about a fix for the 7.30 series, in order to have a final release that works.

**Pull request merged**
