### PR TITLE
Reference for Windows test which currently fails.

### PR DESCRIPTION
**Pull request by melund**
This enables windows testing for Github actions without fixing the errors. 

It is just a reference to what is fixed by #19. #19 also includes these commits and enables windows testing. 

So don't merge this :)

### CODE REVIEW

**Comment by melund** [comment]
Sorry. I think I had a yml syntax error which caused the workflow file to be invalid.

**Comment by melund** [comment]
Pytest reports the following for windows:

```
= 113 failed, 23 passed, 11 skipped, 2 xfailed, 11 warnings in 171.39 seconds =
```

**Comment by johanneskoester** [comment]
With the [failing test](https://github.com/snakemake/snakemake/pull/59/checks?check_run_id=277503801#step:6:264), might there be a linebreak issue?

**Comment by melund** [comment]
> With the [failing test](https://github.com/snakemake/snakemake/pull/59/checks?check_run_id=277503801#step:6:264), might there be a linebreak issue?

@johanneskoester Yes. Line ending issues contributes a significant portion of the errors. So in #19 I modified the tests machinery so it can compare expected outputs while ignoring line endings on windows. 
https://github.com/snakemake/snakemake/pull/19/files#diff-61d51a325171d97c8a56e59ea525339bL30-R38

**Comment by melund** [comment]
@johanneskoester I have updated the pull request that fixes the windows test suite with the original description from bitbucket which explains what the PR does: 
https://github.com/snakemake/snakemake/pull/19#issue-326685340

**Comment by melund** [comment]
I am closing this. It was just a reference to what was fixed by #19

**Pull request closed without merging**
