### PR TITLE
fix: processing in conda yaml and url bug

### PR DESCRIPTION
**Pull request by ShogoAkiyama**
### Description
If conda is url path, `self.is_named` will be true, so this process will result in an error like the following issue.
So I modified the process.

issue: #1674
```
conda env export --name 'URL'
```

fixed like below
```
conda env export --prefix 'URL'
```

### CODE REVIEW

**Comment by ShogoAkiyama** [comment]
issue #1998

**Comment by migrau** [comment]
This works https://github.com/snakemake/snakemake/pull/1708/files
Thanks, @ShogoAkiyama

**Comment by AroneyS** [comment]
@johanneskoester Is there something blocking this pull-request?

**Comment by Unaimend** [comment]
Also encountered this problem today

**Comment by johanneskoester** [comment]
I believe this is already fixed in a different way in the current stable snakemake.

**Pull request closed without merging**
