### PR TITLE
fix: only last daughter process accounted in benchmark cpu time

### PR DESCRIPTION
**Pull request by VPestel**
Solves #2147  by keeping track of CPU times in a dictionary. 

### Description

The CPU time was computed at each call of ``BenchmarkTimer:_update_record`` by looping over the current  ``chain((self.main,), self.main.children(recursive=True))`` and summing the CPU times.

This approach only account for the total CPU times of processes that are still alive when the last ``BenchmarkTimer:_update_record`` is done, so when 2 or more processes are started sequentially, the CPU times value only capture the running time of the last process.

To correct this bug, I propose to replace ``BenchmarkTimer:processed_procs`` by a dictionary and keep track of the total CPU times of all processes spawn by the main current process.  It know gets the proper result when using the example provided in #2147.

### QC

* [ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by VPestel** [comment]
I'm not sure on how to implement a test for this case. Looking at [tests/test_benchmark](https://github.com/snakemake/snakemake/tree/main/tests/test_benchmark) I see it only checks the benchmark files are produced (makes sense, hard to guess what be in it). As it only corrects edge case bug, not sure if we need to test it though.

**Review by johanneskoester — APPROVED** [review]
Thanks a lot for the fix. I think we can live with not really having a direct test. The changes make a lot of sense.

**Comment by johanneskoester** [comment]
May I ask you to run black on the codebase, so that your changes are formatted according to the standards?

**Comment by VPestel** [comment]
> May I ask you to run black on the codebase, so that your changes are formatted according to the standards?

Done !

**Comment by johanneskoester** [comment]
Thanks a lot!

**Pull request merged**
