### PR TITLE
docs: update docs for azbatch and dockerhub ref

### PR DESCRIPTION
**Pull request by jakevc**
### Description

- Patches the Azure Batch Executor docs to include instructions for generating an SAS token
- Updates the Azure Batch Executor test to pull docker image from the latest snakemake release 

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by vsmalladi** [comment]
@jakevc also did some updates in my pr #2299 maybe we can merge the two?

**Comment by jakevc** [comment]
@vsmalladi Nice! I will merge yours into mine... only because then the tests will actually run correctly (mine has access to the secrets) needed for the CI.

**Comment by johanneskoester** [comment]
Maybe caused by an api breakage?

**Comment by jakevc** [comment]
> Maybe caused by an api breakage?

fixed!

**Review by johanneskoester — APPROVED** [review]

**Pull request merged**
