### PR TITLE
feat: allow for human friendly resource definitions (e.g. mem="5GB", runtime="1d")

### PR DESCRIPTION
**Pull request by johanneskoester**
### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Comment by johanneskoester** [comment]
cc @cmeesters

**Comment by cmeesters** [comment]
Thank you, looks great. I have not yet found the time to scrutinize everything, but stumbled across the out commented group-job lines in the slurm_jobstep-executor. The comment there is one we had already. So, is it really meant this way? Or did this change creep in accidentally?

**Comment by cmeesters** [comment]
Or perhaps I overlooked "This branch is out-of-date with the base branch" and the merge with main needs to performed, first?

**Comment by johanneskoester** [comment]
> Thank you, looks great. I have not yet found the time to scrutinize everything, but stumbled across the out commented group-job lines in the slurm_jobstep-executor. The comment there is one we had already. So, is it really meant this way? Or did this change creep in accidentally?

See my comment in issue #2060. I think this PR is unrelated.

**Pull request merged**
