### PR TITLE
[WIP] Adding Google Life Science support

### PR DESCRIPTION
**Pull request by johanneskoester**
Migrated from PR #90.

### CODE REVIEW

**Comment by johanneskoester** [comment]
@vsoch permissions of the service account are not correct yet. Can you adapt them for the github-actions user such that tests run through?

**Comment by johanneskoester** [comment]
Here: https://console.cloud.google.com/iam-admin/iam?project=snakemake-testing

**Comment by vsoch** [comment]
okay looks like the Google Life Sciences tests passed, here are some warnings from pytest:

```
=============================== warnings summary ===============================
snakemake/io.py:979
  /home/runner/work/snakemake/snakemake/snakemake/io.py:979: DeprecationWarning: invalid escape sequence \)
    "(/,\) and must start with '.' (e.g. .txt)."

snakemake/script.py:29
  /home/runner/work/snakemake/snakemake/snakemake/script.py:29: DeprecationWarning: invalid escape sequence \d
    PY_VER_RE = re.compile("Python (?P<ver_min>\d+\.\d+).*")

snakemake/notebook.py:13
  /home/runner/work/snakemake/snakemake/snakemake/notebook.py:13: DeprecationWarning: invalid escape sequence \S
    KERNEL_STARTED_RE = re.compile("Kernel started: (?P<kernel_id>\S+)")

snakemake/notebook.py:14
  /home/runner/work/snakemake/snakemake/snakemake/notebook.py:14: DeprecationWarning: invalid escape sequence \S
    KERNEL_SHUTDOWN_RE = re.compile("Kernel shutdown: (?P<kernel_id>\S+)")

snakemake/resources.py:26
  /home/runner/work/snakemake/snakemake/snakemake/resources.py:26: DeprecationWarning: invalid escape sequence \w
    valid = re.compile("[a-zA-Z_]\w*$")

tests/test_google_lifesciences.py::test_google_lifesciences
  /home/runner/work/snakemake/snakemake/snakemake/remote/__init__.py:244: DeprecationWarning: invalid escape sequence \:
    "^(?P<protocol>[a-zA-Z]+\://)?(?P<host>[A-Za-z0-9\-\.]+)(?:\:(?P<port>[0-9]+))?(?P<path_remainder>.*)$",

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================== 1 passed, 6 warnings in 375.65s (0:06:15) ===================
```
I think thee were probably already there, but let me know if you want me to open an issue so we can look into addressing.

**Comment by johanneskoester** [comment]
Awesome, time to merge!

**Comment by johanneskoester** [comment]
The warnings are old, but if you like, please provide a separate PR for finally fixing them :-)

**Pull request merged**
