### PR TITLE
fix: issue with aggregated checkpoint output on GLS

### LINKED ISSUE #2021: Strange behavior when using checkpoints in cloud execution
**Snakemake version**

`7.18.2`
**Describe the bug**

I am trying to run a workflow with a checkpoint in the cloud. The workflow runs as expected when executed locally.  However,  in the cloud (using `--google-lifesciences`) it seems that on the checkpoint aggregating step (see below), the whole DAG is rebuilt within that cloud job. 

**Minimal example**

```
import glob

localrules: first_step, second_step
samples = ["sample_a"]
rule all:
    input: expand("results/{sample}/done.txt", sample=samples)

def get_files(wc):
    """
    Globs files from second_step's output to create input for third_step
    """
    checkpoint_output = checkpoints.second_step.get(**wc).output[0]
    query = os.path.join(checkpoint_output, "*.txt") # only care about txt files
    files = [os.path.basename(f) for f in glob.glob(query)]
    numbers = [f.replace("_interval.txt", "") for f in files]
    
    out = expand("results/{{sample}}/third_step/intermediate_{i}.txt", i=numbers)
    
    return out
    
rule first_step:
    output: "results/{sample}/hi.txt"
    shell: "echo 'hi' > {output}"

checkpoint second_step:
    """
    Generates random number of files
    """
    input: "results/{sample}/hi.txt"
    output: directory("results/{sample}/second_step")
    run:
        import random
        import os
        num = random.randint(1,10)
        if not os.path.exists(output[0]):
            os.mkdir(output[0])
        for i in range(num):
            with open(os.path.join(output[0], f"{i}_interval.txt"), "w") as f:
                print(f"this is a message from file interval_{i}.txt", file=f)

rule third_step:
    input: "results/{sample}/second_step/{i}_interval.txt"
    output: "results/{sample}/third_step/intermediate_{i}.txt"
    shell: "cat {input} > {output}"


rule aggregate_step:
    """
    Aggregates files from third_step
    """
    input: get_files
    output: "results/{sample}/done.txt"
    shell: "cat {input} > {output}"
```
run using:
`snakemake --google-lifesciences --default-remote-prefix cade-test -j 10`

This is the stdout/stderr from the aggregate_step job, notice how it rebuilds the DAG
```
--2022-12-17 05:53:54--  https://raw.githubusercontent.com/snakemake/snakemake/main/snakemake/executors/google_lifesciences_helper.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4045 (4.0K) [text/plain]
Saving to: â€˜/download.pyâ€™

     0K ...                                                   100% 4.19M=0.001s

2022-12-17 05:53:54 (4.19 MB/s) - â€˜/download.pyâ€™ saved [4045/4045]

Blob source/cache/workdir-b03670b5fb7cb25f93b093b879059c6fcfe6a93aed77fa6984cb8c5645a4d322.tar.gz downloaded to /tmp/workdir.tar.gz.
Snakefile
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=1000, disk_mb=1000
Select jobs to execute...

[Sat Dec 17 05:53:59 2022]
localcheckpoint second_step:
    input: cade-test/results/sample_a/hi.txt
    output: cade-test/results/sample_a/second_step
    jobid: 1
    reason: Missing output files: cade-test/results/sample_a/second_step
    wildcards: sample=sample_a
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp
Downstream jobs will be updated after completion.

Warning: the following output files of rule second_step were not present when the DAG was created:
{'cade-test/results/sample_a/second_step'}
Downloading from remote: cade-test/results/sample_a/hi.txt
Finished download.
Uploading to remote: cade-test/results/sample_a/second_step
Finished upload.
[Sat Dec 17 05:54:00 2022]
Finished job 1.
1 of 2 steps (50%) done
Select jobs to execute...

[Sat Dec 17 05:54:01 2022]
rule third_step:
    input: cade-test/results/sample_a/second_step/0_interval.txt
    output: cade-test/results/sample_a/third_step/intermediate_0.txt
    jobid: 5
    reason: Updated input files: cade-test/results/sample_a/second_step/0_interval.txt
    wildcards: sample=sample_a, i=0
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp

Downloading from remote: cade-test/results/sample_a/second_step/0_interval.txt
Finished download.
Uploading to remote: cade-test/results/sample_a/third_step/intermediate_0.txt
Finished upload.
[Sat Dec 17 05:54:02 2022]
Finished job 5.
2 of 4 steps (50%) done
Select jobs to execute...

[Sat Dec 17 05:54:02 2022]
rule third_step:
    input: cade-test/results/sample_a/second_step/1_interval.txt
    output: cade-test/results/sample_a/third_step/intermediate_1.txt
    jobid: 6
    reason: Updated input files: cade-test/results/sample_a/second_step/1_interval.txt
    wildcards: sample=sample_a, i=1
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp

Downloading from remote: cade-test/results/sample_a/second_step/1_interval.txt
Finished download.
Uploading to remote: cade-test/results/sample_a/third_step/intermediate_1.txt
Finished upload.
[Sat Dec 17 05:54:03 2022]
Finished job 6.
3 of 4 steps (75%) done
Select jobs to execute...

[Sat Dec 17 05:54:03 2022]
rule aggregate_step:
    input: cade-test/results/sample_a/third_step/intermediate_0.txt, cade-test/results/sample_a/third_step/intermediate_1.txt
    output: cade-test/results/sample_a/done.txt
    jobid: 0
    reason: Input files updated by another job: cade-test/results/sample_a/third_step/intermediate_1.txt, cade-test/results/sample_a/third_step/intermediate_0.txt
    wildcards: sample=sample_a
    resources: mem_mb=1000, disk_mb=1000, tmpdir=/tmp

Uploading to remote: cade-test/results/sample_a/done.txt
Finished upload.
[Sat Dec 17 05:54:04 2022]
Finished job 0.
4 of 4 steps (100%) done
['results/{sample}/third_step/intermediate_0.txt', 'results/{sample}/third_step/intermediate_1.txt']
--2022-12-17 05:54:06--  https://raw.githubusercontent.com/snakemake/snakemake/main/snakemake/executors/google_lifesciences_helper.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4045 (4.0K) [text/plain]
Saving to: â€˜/gls.pyâ€™

     0K ...                                                   100% 4.37M=0.001s

2022-12-17 05:54:06 (4.37 MB/s) - â€˜/gls.pyâ€™ saved [4045/4045]

```

**Additional context**
@johanneskoester Would appreciate your insight on this. Am I doing something really wrong or not using checkpoints as intended?

### PR DESCRIPTION
**Pull request by aryarm**
resolves #2021

### Description
PR #1294 (from a year ago) added a simple test for checkpoints on the cloud.

This PR adds tests for a more complicated example where the output of the checkpoint is now aggregated over wildcards. In this case, we are trying to reproduce the behavior in #2021, in which Snakemake might be
1. rebuilding the DAG when it doesn't need to be and
2. applying the remote prefix to the checkpoint output more than once (as it did in #574)

Note that this PR does not yet contain a fix for the strange behavior. Our hope is just to reproduce things with the test suite at the moment. As noted in https://github.com/snakemake/snakemake/issues/574#issuecomment-701870887, it can be difficult to debug issues on the cloud because Snakemake redeploys a different version of itself in each cloud instance. But labeling this PR with `update-container-image` allows us to deploy a temporary version of the code from this PR.

### QC
* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).
    The docs do not need updating in this case, since this PR simply adds tests and fixes a bug.

### CODE REVIEW

**Comment by aryarm** [comment]
hmm looks like the tests passed

So at first glance, it seems like we might have failed to reproduce the issue. But then I looked through the logs and couldn't find any sign that our tests were executed.

@johanneskoester, why is this line commented out on main? That seems to be the reason it didn't run.
https://github.com/snakemake/snakemake/blob/2a4b9b663c148f80085f4ec651c537257c1319e4/.github/workflows/main.yml#L231

**Comment by cademirch** [comment]
Looking at the comments in #574, I believe @vsoch's [proposed solution](https://github.com/snakemake/snakemake/issues/574#issuecomment-677689308) to check for the remote prefix in `self.workflow.apply_default_remote(value)` would probably the way to go in order to fix the double prefix in this scenario. Since in this case the user is applying the default prefix in the input function by using an absolute path, I'm not sure I can think of another way.

**Comment by cademirch** [comment]
It has been a while since I started digging into this, and I think I've come up with a candidate solution. 

To use a checkpoint's output we use this function: 
https://github.com/snakemake/snakemake/blob/bdde680f01b5d276c68ef2d7ef71536e6d976652/snakemake/checkpoints.py#L25

Which returns the checkpoint's output for a set of wildcards if it has been produced. However, the function does not check if the checkpoint output exists remotely, and this is why when the DAG is built on the cloud node, it includes the checkpoint before the target job.

My proposed solution is to check if the checkpoint output exists remotely and if so download it, thus allowing the workflow to be run only using the target rule.

Proposed solution:

```python
def get(self, **wildcards):
        missing = self.rule.wildcard_names.difference(wildcards.keys())
        if missing:
            raise WorkflowError(
                "Missing wildcard values for {}".format(", ".join(missing))
            )

        output, _ = self.rule.expand_output(wildcards)
        if self.checkpoints.future_output is not None:
            for iofile in output:
                if iofile.exists_remote and not iofile.exists_local:
                    iofile.download_from_remote()
                    return CheckpointJob(self.rule, output)
                if iofile in self.checkpoints.future_output:
                    break
                if not iofile.exists and not iofile.is_temp:
                    break
            else:
                return CheckpointJob(self.rule, output)
        raise IncompleteCheckpointException(self.rule, checkpoint_target(output[0]))
```

I have tested this locally by keeping the checkpoint output files remotely and it seems to work well. Would appreciate any feedback @aryarm @johanneskoester. Let me know if I can provide any more info or clarity! 

I will commit this change to this PR soon.

**Comment by cademirch** [comment]
See #2220, @aryarm if you could close this PR in favor for that one, that would be great, thanks!

**Comment by aryarm** [comment]
Sure thing! Thanks for taking all of this on, @cademirch . Looking forward to seeing the fixes!

**Pull request closed without merging**
