### PR TITLE
fix: allowing trailing '+' in name patterns

### PR DESCRIPTION
**Pull request by cmeesters**
This PR should fix issue #3001: 

A workflow might contain simple regexes within Python code, e.g. `r"\s+"`. Prior to this PR the `NAME_PATTERN` of the linter considered this first part, the `s` as part of a string to be concatenated with a path. 

### QC

There is no additional test (yet. Not sure it needs one). Docs do not need updating as the intended behaviour does not change.

* [ ] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [ ] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

## Summary by CodeRabbit

- **New Features**
	- Improved name validation logic by updating the regex pattern, ensuring that file names do not end with a '+' character, reducing the risk of unintended exclusions.

- **Documentation**
	- Added comments to clarify the implications of the regex changes and to suggest alternatives for different separator needs.

### CODE REVIEW

**Comment by cmeesters** [comment]
brrrr, I consider this failure unrelated to the PR:

```
=========================== short test summary info ============================
FAILED tests/tests.py::test_paramspace - AssertionError: wrong result produced for file 'results/sep/simulations/alpha_is_2/beta_is_0.0/gamma_is_3.9.tsv':
------found------
{'alpha': np.int64(2), 'beta': np.float64(0.0), 'gamma': np.float64(3.9)}
-----expected-----
{'alpha': 2, 'beta': 0.0, 'gamma': 3.9}
-----------------
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
========= 1 failed, 22 passed, 306 deselected, 111 warnings in 51.20s ==========
```
But, of course, the rest will not run.

**Comment by johanneskoester** [comment]
Seems like the floats are not correctly converted into plain string representations. A fix would be greatly appreciated, I don't have any time in the next days.

**Comment by cmeesters** [comment]
Already thought, that a fix might be trivial, but whether I will find the time ... Let's see.

**Comment by cmeesters** [comment]
Definitively not trivial. We could:

- change the expected results to meet the code output. 
- change the test.
- change the actual code. I found the spot, it's a tiny lambda function, which could be extended.

All three options sound like tinkering to me.

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thank you!

**Comment by cmeesters** [comment]
Thank you for the swift review!

**Comment by zhangxiaoxing** [comment]
I'm a bit confused here, as a long-running snakefile now produces a new warning:
`"/path/to/snakefile:666: SyntaxWarning: invalid escape sequence '\d'"`
The line number could not be easily matched back in the snakefile, but somewhere I do have such a line:
```
output:
    "output/outputfile_{index,\d+}.out"
```
This is to limit the wildcard matching to only digits. Should I ignore the warning? Should I update the rules? Should I provide more detail?

Thanks!

**Comment by cmeesters** [comment]
Thanks for reporting this!!!

You may ignore the warning. I will not. Can you please indicate the entire rule? Is there, perhaps, more detail to the warning message?

Actually, this PR _only_ affected the linter, not the Snakemake core. So, this might be totally unrelated. But we should sort this out, before perhaps opening a full issue.

**Comment by cmeesters** [comment]
Ah, yes, this alone is a faulty syntax expression. Try

```Python
output:
     r"test{num,\d+}.txt"
```

**Comment by zhangxiaoxing** [comment]
> Ah, yes, this alone is a faulty syntax expression. Try
> 
> ```python
> output:
>      r"test{num,\d+}.txt"
> ```

That indeed fixed the warning. Thanks.

**Comment by zhangxiaoxing** [comment]
> Ah, yes, this alone is a faulty syntax expression. Try
> 
> ```python
> output:
>      r"test{num,\d+}.txt"
> ```

Still I suggest the documentation to be refined. Currently it's still showing this faulty syntax...
image

**Comment by cmeesters** [comment]
ah, thanks. It's a Python thing. Will fix the docs.

**Pull request merged**
