### PR TITLE
a suggested fix for directory support in Snakefile for GLS

### PR DESCRIPTION
**Pull request by vsoch**
This fix cannot be tested because I currently dont have access to a Google Cloud account, but Ill open it for review and discussion. This PR also depends on #665 - we won't be able to get to the remote upload step given that the path is not flagged as a directory.

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Good catch. Can you extend the test case, such that the new code block is checked? Then, there is no need for manual testing anyway.

**Comment by vsoch** [comment]
@johanneskoester if I add to the GLS test, it would only run if it's on a branch of this repository (it will skip on my account). Is this what you are suggesting to do?

**Comment by johanneskoester** [comment]
Yes, that's fine, we'll just merge into a new branch in the main repo. You can work in the main repo directly in the future. 

```
import os

# This test file is taken from Kubernetes - both use Google Cloud
from snakemake.remote.GS import RemoteProvider as GSRemoteProvider
GS = GSRemoteProvider()

rule all:
    input:
        "landsat-data.txt.bz2",
        "testdir"

rule copy:
    input:
        GS.remote("gcp-public-data-landsat/LC08/01/001/003/LC08_L1GT_001003_20170430_20170501_01_RT/LC08_L1GT_001003_20170430_20170501_01_RT_MTL.txt")
    output:
        "landsat-data.txt"
    resources:
        mem_mb=100
    run:
        # we could test volume size like this but it is currently unclear what f1-micro instances provide as boot disk size
        #stats = os.statvfs('.')
        #volume_gib = stats.f_bsize * stats.f_blocks / 1.074e9
        #assert volume_gib > 90
        shell("cp {input} {output}")

rule pack:
    input:
        "landsat-data.txt"
    output:
        "landsat-data.txt.bz2"
    conda:
        "env.yml"
    log:
        "logs/pack.log"
    shell:
        "bzip2 -c {input} > {output}; echo successful > {log}"


rule directory:
    output:
        directory("testdir")
    log:
        "logs/directory.log"
    shell:
        "mkdir -p {output}; touch {output}/test.txt"
```

**Comment by vsoch** [comment]
Closing in favor of #691

**Pull request closed without merging**
