### PR TITLE
automatic containerization with --containerize

### PR DESCRIPTION
**Pull request by johanneskoester**
Adds a new flag `snakemake --containerize` to automatically generate a container image like this:

```
FROM condaforge/mambaforge:latest
LABEL io.github.snakemake.containerized="true"
LABEL io.github.snakemake.conda_env_hash="f0278bdd2a1e677aae8b0f8d0d8c676a52d96454cfa190a7efce1b9f6a5b3017"

# Step 1: Retrieve conda environments

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.59.2/bio/samtools/faidx/environment.yaml
#   prefix: /conda-envs/0c4258f467d23fdc05f5b411edc5f92d
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - samtools ==1.10
RUN mkdir -p /conda-envs/0c4258f467d23fdc05f5b411edc5f92d
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.59.2/bio/samtools/faidx/environment.yaml /conda-envs/0c4258f467d23fdc05f5b411edc5f92d/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.68.0/bio/freebayes/environment.yaml
#   prefix: /conda-envs/252b2e21b4cafd96ce409210b35f5a98
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - freebayes =1.3.1
#     - bcftools =1.11
#     - parallel =20190522
#     - bedtools >=2.29
#     - sed =4.7
RUN mkdir -p /conda-envs/252b2e21b4cafd96ce409210b35f5a98
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.68.0/bio/freebayes/environment.yaml /conda-envs/252b2e21b4cafd96ce409210b35f5a98/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/bcftools/concat/environment.yaml
#   prefix: /conda-envs/d162aa4e18ad473939bd61fec09c888e
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - bcftools =1.11
RUN mkdir -p /conda-envs/d162aa4e18ad473939bd61fec09c888e
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/bcftools/concat/environment.yaml /conda-envs/d162aa4e18ad473939bd61fec09c888e/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/bwa/index/environment.yaml
#   prefix: /conda-envs/4d892d9b9b724d74b80c44fc06677208
#   channels:
#     - bioconda
#     - conda-forge
#     - defaults
#   dependencies:
#     - bwa ==0.7.17
RUN mkdir -p /conda-envs/4d892d9b9b724d74b80c44fc06677208
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/bwa/index/environment.yaml /conda-envs/4d892d9b9b724d74b80c44fc06677208/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/bwa/mem/environment.yaml
#   prefix: /conda-envs/9d5b99f33493a0a477e90f484cd51518
#   channels:
#     - bioconda
#     - conda-forge
#     - defaults
#   dependencies:
#     - bwa ==0.7.17
#     - samtools ==1.9
#     - picard ==2.20.1
RUN mkdir -p /conda-envs/9d5b99f33493a0a477e90f484cd51518
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/bwa/mem/environment.yaml /conda-envs/9d5b99f33493a0a477e90f484cd51518/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/fastqc/environment.yaml
#   prefix: /conda-envs/35c260b1370c2e182fdeba6a2defc5b1
#   channels:
#     - bioconda
#     - conda-forge
#     - defaults
#   dependencies:
#     - fastqc ==0.11.9
RUN mkdir -p /conda-envs/35c260b1370c2e182fdeba6a2defc5b1
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/fastqc/environment.yaml /conda-envs/35c260b1370c2e182fdeba6a2defc5b1/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/multiqc/environment.yaml
#   prefix: /conda-envs/267449ceba33589114e57ca3f5a2cf92
#   channels:
#     - bioconda
#     - conda-forge
#     - defaults
#   dependencies:
#     - multiqc ==1.9
RUN mkdir -p /conda-envs/267449ceba33589114e57ca3f5a2cf92
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/multiqc/environment.yaml /conda-envs/267449ceba33589114e57ca3f5a2cf92/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/picard/markduplicates/environment.yaml
#   prefix: /conda-envs/24383da45ac66a8b2cf72a35a3835494
#   channels:
#     - bioconda
#     - conda-forge
#     - defaults
#   dependencies:
#     - picard ==2.22.1
#     - snakemake-wrapper-utils ==0.1.3
RUN mkdir -p /conda-envs/24383da45ac66a8b2cf72a35a3835494
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/picard/markduplicates/environment.yaml /conda-envs/24383da45ac66a8b2cf72a35a3835494/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/samtools/calmd/environment.yaml
#   prefix: /conda-envs/8ed909efa67419cf2da4cf8b44e4318a
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - samtools ==1.11
RUN mkdir -p /conda-envs/8ed909efa67419cf2da4cf8b44e4318a
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/samtools/calmd/environment.yaml /conda-envs/8ed909efa67419cf2da4cf8b44e4318a/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/tabix/environment.yaml
#   prefix: /conda-envs/8cf6cd77c4a5511d24e27fd3e2f60de5
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - htslib ==1.10
RUN mkdir -p /conda-envs/8cf6cd77c4a5511d24e27fd3e2f60de5
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/tabix/environment.yaml /conda-envs/8cf6cd77c4a5511d24e27fd3e2f60de5/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/vep/plugins/environment.yaml
#   prefix: /conda-envs/74e900c93519f6cc6efa7dc4f141d5be
#   channels:
#     - conda-forge
#   dependencies:
#     - python =3
RUN mkdir -p /conda-envs/74e900c93519f6cc6efa7dc4f141d5be
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.69.0/bio/vep/plugins/environment.yaml /conda-envs/74e900c93519f6cc6efa7dc4f141d5be/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.70.0/bio/fastp/environment.yaml
#   prefix: /conda-envs/2dae0496cdef227fbafc830829f60fcb
#   channels:
#     - bioconda
#     - conda-forge
#     - defaults
#   dependencies:
#     - fastp =0.20
RUN mkdir -p /conda-envs/2dae0496cdef227fbafc830829f60fcb
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.70.0/bio/fastp/environment.yaml /conda-envs/2dae0496cdef227fbafc830829f60fcb/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/0.70.0/bio/kallisto/index/environment.yaml
#   prefix: /conda-envs/23192f70514e5d8052a6d57836009ef7
#   channels:
#     - bioconda
#     - conda-forge
#     - defaults
#   dependencies:
#     - kallisto ==0.45.0
RUN mkdir -p /conda-envs/23192f70514e5d8052a6d57836009ef7
ADD https://github.com/snakemake/snakemake-wrappers/raw/0.70.0/bio/kallisto/index/environment.yaml /conda-envs/23192f70514e5d8052a6d57836009ef7/environment.yaml

# Conda environment:
#   source: https:/github.com/snakemake/snakemake-wrappers/raw/vep-nocache/bio/vep/annotate/environment.yaml
#   prefix: /conda-envs/9b5b117589e63dc251d6034b16aac7ce
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - ensembl-vep =101
#     - bcftools =1.9
RUN mkdir -p /conda-envs/9b5b117589e63dc251d6034b16aac7ce
ADD https://github.com/snakemake/snakemake-wrappers/raw/vep-nocache/bio/vep/annotate/environment.yaml /conda-envs/9b5b117589e63dc251d6034b16aac7ce/environment.yaml

# Conda environment:
#   source: workflow/envs/bcftools.yaml
#   prefix: /conda-envs/344e3c4b237256211d5d8837042abafa
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - bcftools =1.10
RUN mkdir -p /conda-envs/344e3c4b237256211d5d8837042abafa
COPY workflow/envs/bcftools.yaml /conda-envs/344e3c4b237256211d5d8837042abafa/environment.yaml

# Conda environment:
#   source: workflow/envs/entrez.yaml
#   prefix: /conda-envs/7ad98aea2f3a2f15c9d8f471e3076dbd
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - entrez-direct =13.9
RUN mkdir -p /conda-envs/7ad98aea2f3a2f15c9d8f471e3076dbd
COPY workflow/envs/entrez.yaml /conda-envs/7ad98aea2f3a2f15c9d8f471e3076dbd/environment.yaml

# Conda environment:
#   source: workflow/envs/mason.yaml
#   prefix: /conda-envs/e5d57e294bce34aa153153055f032b6a
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - mason =2.0
RUN mkdir -p /conda-envs/e5d57e294bce34aa153153055f032b6a
COPY workflow/envs/mason.yaml /conda-envs/e5d57e294bce34aa153153055f032b6a/environment.yaml

# Conda environment:
#   source: workflow/envs/megahit.yaml
#   prefix: /conda-envs/20ffb526de7f8759463258a670541d62
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - megahit = 1.2.9
RUN mkdir -p /conda-envs/20ffb526de7f8759463258a670541d62
COPY workflow/envs/megahit.yaml /conda-envs/20ffb526de7f8759463258a670541d62/environment.yaml

# Conda environment:
#   source: workflow/envs/pangolin.yaml
#   prefix: /conda-envs/bdec4c2bfe2cf7bfed73f060727d59e1
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - pangolin =2.1.7
RUN mkdir -p /conda-envs/bdec4c2bfe2cf7bfed73f060727d59e1
COPY workflow/envs/pangolin.yaml /conda-envs/bdec4c2bfe2cf7bfed73f060727d59e1/environment.yaml

# Conda environment:
#   source: workflow/envs/python.yaml
#   prefix: /conda-envs/f0b49445fc10e5568324275239d44fff
#   channels:
#     - conda-forge
#   dependencies:
#     - python =3.9
#     - pandas =1.2
#     - jupyter =1.0
#     - altair =4.1
#     - altair_saver =0.5
RUN mkdir -p /conda-envs/f0b49445fc10e5568324275239d44fff
COPY workflow/envs/python.yaml /conda-envs/f0b49445fc10e5568324275239d44fff/environment.yaml

# Conda environment:
#   source: workflow/envs/rbt.yaml
#   prefix: /conda-envs/26d47b0350af034ed4eb547569d2b690
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - rust-bio-tools =0.18.1
RUN mkdir -p /conda-envs/26d47b0350af034ed4eb547569d2b690
COPY workflow/envs/rbt.yaml /conda-envs/26d47b0350af034ed4eb547569d2b690/environment.yaml

# Conda environment:
#   source: workflow/envs/tabix.yaml
#   prefix: /conda-envs/19484316fcc7bbb44edf841daed14a35
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - tabix =0.2.6
#     - curl
RUN mkdir -p /conda-envs/19484316fcc7bbb44edf841daed14a35
COPY workflow/envs/tabix.yaml /conda-envs/19484316fcc7bbb44edf841daed14a35/environment.yaml

# Conda environment:
#   source: workflow/envs/unix.yaml
#   prefix: /conda-envs/b48d81c41e5c601aea2aaaa064a8a066
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - curl
#     - sed
RUN mkdir -p /conda-envs/b48d81c41e5c601aea2aaaa064a8a066
COPY workflow/envs/unix.yaml /conda-envs/b48d81c41e5c601aea2aaaa064a8a066/environment.yaml

# Conda environment:
#   source: workflow/envs/varlociraptor.yaml
#   prefix: /conda-envs/e14a4a44fc4f040c99156c86f6da1825
#   channels:
#     - bioconda
#     - conda-forge
#   dependencies:
#     - varlociraptor =2.6.0
RUN mkdir -p /conda-envs/e14a4a44fc4f040c99156c86f6da1825
COPY workflow/envs/varlociraptor.yaml /conda-envs/e14a4a44fc4f040c99156c86f6da1825/environment.yaml

# Step 2: Generate conda environments

RUN mamba env create --prefix /conda-envs/0c4258f467d23fdc05f5b411edc5f92d --file /conda-envs/0c4258f467d23fdc05f5b411edc5f92d/environment.yaml && \
    mamba env create --prefix /conda-envs/252b2e21b4cafd96ce409210b35f5a98 --file /conda-envs/252b2e21b4cafd96ce409210b35f5a98/environment.yaml && \
    mamba env create --prefix /conda-envs/d162aa4e18ad473939bd61fec09c888e --file /conda-envs/d162aa4e18ad473939bd61fec09c888e/environment.yaml && \
    mamba env create --prefix /conda-envs/4d892d9b9b724d74b80c44fc06677208 --file /conda-envs/4d892d9b9b724d74b80c44fc06677208/environment.yaml && \
    mamba env create --prefix /conda-envs/9d5b99f33493a0a477e90f484cd51518 --file /conda-envs/9d5b99f33493a0a477e90f484cd51518/environment.yaml && \
    mamba env create --prefix /conda-envs/35c260b1370c2e182fdeba6a2defc5b1 --file /conda-envs/35c260b1370c2e182fdeba6a2defc5b1/environment.yaml && \
    mamba env create --prefix /conda-envs/267449ceba33589114e57ca3f5a2cf92 --file /conda-envs/267449ceba33589114e57ca3f5a2cf92/environment.yaml && \
    mamba env create --prefix /conda-envs/24383da45ac66a8b2cf72a35a3835494 --file /conda-envs/24383da45ac66a8b2cf72a35a3835494/environment.yaml && \
    mamba env create --prefix /conda-envs/8ed909efa67419cf2da4cf8b44e4318a --file /conda-envs/8ed909efa67419cf2da4cf8b44e4318a/environment.yaml && \
    mamba env create --prefix /conda-envs/8cf6cd77c4a5511d24e27fd3e2f60de5 --file /conda-envs/8cf6cd77c4a5511d24e27fd3e2f60de5/environment.yaml && \
    mamba env create --prefix /conda-envs/74e900c93519f6cc6efa7dc4f141d5be --file /conda-envs/74e900c93519f6cc6efa7dc4f141d5be/environment.yaml && \
    mamba env create --prefix /conda-envs/2dae0496cdef227fbafc830829f60fcb --file /conda-envs/2dae0496cdef227fbafc830829f60fcb/environment.yaml && \
    mamba env create --prefix /conda-envs/23192f70514e5d8052a6d57836009ef7 --file /conda-envs/23192f70514e5d8052a6d57836009ef7/environment.yaml && \
    mamba env create --prefix /conda-envs/9b5b117589e63dc251d6034b16aac7ce --file /conda-envs/9b5b117589e63dc251d6034b16aac7ce/environment.yaml && \
    mamba env create --prefix /conda-envs/344e3c4b237256211d5d8837042abafa --file /conda-envs/344e3c4b237256211d5d8837042abafa/environment.yaml && \
    mamba env create --prefix /conda-envs/7ad98aea2f3a2f15c9d8f471e3076dbd --file /conda-envs/7ad98aea2f3a2f15c9d8f471e3076dbd/environment.yaml && \
    mamba env create --prefix /conda-envs/e5d57e294bce34aa153153055f032b6a --file /conda-envs/e5d57e294bce34aa153153055f032b6a/environment.yaml && \
    mamba env create --prefix /conda-envs/20ffb526de7f8759463258a670541d62 --file /conda-envs/20ffb526de7f8759463258a670541d62/environment.yaml && \
    mamba env create --prefix /conda-envs/bdec4c2bfe2cf7bfed73f060727d59e1 --file /conda-envs/bdec4c2bfe2cf7bfed73f060727d59e1/environment.yaml && \
    mamba env create --prefix /conda-envs/f0b49445fc10e5568324275239d44fff --file /conda-envs/f0b49445fc10e5568324275239d44fff/environment.yaml && \
    mamba env create --prefix /conda-envs/26d47b0350af034ed4eb547569d2b690 --file /conda-envs/26d47b0350af034ed4eb547569d2b690/environment.yaml && \
    mamba env create --prefix /conda-envs/19484316fcc7bbb44edf841daed14a35 --file /conda-envs/19484316fcc7bbb44edf841daed14a35/environment.yaml && \
    mamba env create --prefix /conda-envs/b48d81c41e5c601aea2aaaa064a8a066 --file /conda-envs/b48d81c41e5c601aea2aaaa064a8a066/environment.yaml && \
    mamba env create --prefix /conda-envs/e14a4a44fc4f040c99156c86f6da1825 --file /conda-envs/e14a4a44fc4f040c99156c86f6da1825/environment.yaml && \
    mamba clean --all -y

```

which can then be uploaded somewhere (e.g. at quay.io) and used in the Snakefile:

```
container: "docker://quay.io/myusername/myworkflowimage"
```

To provide containerized execution using the very same conda environments as defined in the Snakemake, just already preinstalled in the container.

# TODO
* [x] docs

### CODE REVIEW

**Comment by johanneskoester** [comment]
cc @folker

**Comment by johanneskoester** [comment]
cc @nh13

**Comment by nh13** [comment]
@johanneskoester I think this is great, as now we can automatically create a container given the list of environments.  Kudos!

1. Why are all the environments created in one layer?  That means if any environments file is changed or one added, all of them are rebuilt.  Perhaps you want to try to shove everything into one layer to keep container size small?
2. Why not do a multi-stage build?  You can have a base/builder stage to install system packages and mamba/conda, then a stage per conda environment (eg. `FROM builder as conda-01234..9`, then you can have a final build stage to copy all the environments into the final container (eg. `COPY --from=conda-01234..9  /opt/conda/. /opt/conda/`).
3. If you make a change suggested in (1) or (2), then I'd worry about wanting to control the order in which the conda environments are built.  I'd rather have environments that I know are not going to be updated frequently built first, and so on.  
4. I'd recommend cleaning up the conda installs to reduce image size: `mamba env create && conda clean -afy && find /opt/conda/ -follow -type f -name '*.pyc' -delete`
5. Not everything can be installed from `conda`.  Frequently we will want to install custom tools and executables.   There's no way to do this without post-facto modifying the Dockerfile.
6. There's no way to (i) use a different base image, (ii) customize the Dockerfile (has to be done manually) (eg. install awscliv2)
  
I also prefer centralizing conda requirements files so I can easily see and update dependencies that are common across environments.  Hence why I built [conda-env-builder](https://github.com/nh13/conda-env-builder#why) to support specifying multiple conda environments in one place, and remove redundancy through defaults and inheritance.  The latter also supports arbitrary code to be run after the conda environment is created (to install into the env), which can be run in a dockerfile.  End soap box.

**Comment by johanneskoester** [comment]
Thanks for your feedback @nh13!
Regarding your points:
1. I considered separate layers. However, (as you also imply in a later point) if one layer before (e.g. the corresponding environment) changes, all layers beneath have to be rebuilt and stored again as well. Granted sometimes if the change is at one of the "late" envs the ones at the beginning would not need to be changed. So, as you suggest, one would only really benefit from it if it is possible to properly order the envs. However, there is one other benefit from using a single layer, and that is the fact that conda makes use of hard-linking to avoid copying binaries into the envs. As far as I know though, hard links are turned into copies when the cross layers. Hence, we would artificially bloat the resulting container.
2. When we copy the files in a multi-stage built, we would copy the envs from their prefixes, thereby turning all links into true files, such that we generate potentially a lot of redundantly stored dependencies. My feeling is that copying while preserving the hardlinks is likely not possible. However, if you know a way to preserve the links while doing the copy, we could switch to a multi-stage represenation (also in a later release).
3. Indeed, when using one layer per env, that would be nice, but cumbersome to define. One could order them by modification date, but that only works if the workflow has been already developed for a while. Together with the disadvantage of not being able to benefit from the hard links, I think it is not worth it.
4. We do that already, at the end of the mamba commands.
5. Good point. We could offer to optionally provide a template dockerfile to containerize, e.g. with a {content} where Snakemake will put its generated code.
6. Can be solved via the template (see 5.).

Thanks for pointing to conda-env-builder. I think part of that would be nice to have integrated in Snakemake, e.g. as a flag `--update-conda-envs` or so, that goes through all envs, and tries to raise the versions while minimizing the number of dependencies that aren't shared. Also it could automatically add versions to envs where people haven't specified them. This would make it particularly easy to specify them (just enter the names) and then the flag would add the latest reasonable versions.

**Pull request merged**
