### PR TITLE
feat: Support for machine_type for kubernetes executor

### PR DESCRIPTION
**Pull request by cademirch**
### Description
Quick little feature addition so that Snakemake respects the `machine_type` resource specification when using the Kubernetes executor. See #1278.  

### QC

* [x] The PR contains a test case for the changes or the changes are already covered by an existing test case.
* [x] The documentation (`docs/`) is updated to reflect the changes or this is not necessary (e.g. if the change does neither modify the language nor the behavior or functionalities of Snakemake).

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Thanks a lot! Can you please also add this to the kubernetes section in the snakemake docs?

**Comment by cademirch** [comment]
> Thanks a lot! Can you please also add this to the kubernetes section in the snakemake docs?

Done! 40a5d31

**Comment by cademirch** [comment]
@johanneskoester gentle bump on this. Let me know if you need anything else to close this PR.

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thanks, very good idea! Can you please run black on the changed file for the formatting?

**Pull request merged**
