### PR TITLE
Stata support

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
This introduces integration with Stata (https://www.stata.com/). Documentation and tests are to be added.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Thank you! This is indeed a good idea. How would we test it though? As far as I know, stata is not available as FOSS?
Apart from that, this PR has to wait on PR #101 because in there, we are currently refactoring and cleaning up script support.

**Comment by SultanOrazbayev** [comment]
Would the following work? Running a python-based test that verifies Stata syntax based on pre-defined rules rather than actually calling Stata (which is not available for free). 

Another alternative is to write a Stata-specific program, but also not sure how well the Python integration will work (in the latest version).

Still need to work on the documentation and testing, but will wait for PR#101.

**Comment by johanneskoester** [comment]
The PR is merged, but I still think that it is not a good idea to integrate closed-source software like this. We will never be able to automatically test if it still works in the future. Unless stata provides us with some way to really execute a test in CI, I don't see a way here.

**Comment by johanneskoester** [comment]
Closing because of above reason. Please feel free to reopen if the situation changes.

**Comment by SultanOrazbayev** [comment]
Perhaps the best way forward is to make a separate repo that adds the stata functionality as a separate 'plug-in', not unlike the https://github.com/mbhall88/snakefmt.

**Pull request closed without merging**
